swagger: "2.0"
info:
  description: "Aggregator API for data needed for homepage frontend"
  version: "0.1.0"
  title: "Homepage"
  contact:
    email: "chris@snyder616.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "homepage"
basePath: "/"
tags:
- name: "homepage"
  description: "Homepage operations"
schemes:
- "http"
paths:
  /homepage/{userId}:
    get:
      tags:
      - "homepage"
      summary: "Retrieve homepage data"
      description: ""
      operationId: "getHomepageById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID of user for which to retrieve homepage"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Homepage"
        404:
          description: "Homepage not found for provided user ID"
definitions:
  Homepage:
    type: "object"
    properties:
      user:
        $ref: "#/definitions/HomepageUserInfo"
      newsItems:
        type: "array"
        items:
          $ref: "#/definitions/HomepageNewsItem"
  HomepageUserInfo:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  HomepageNewsItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
