swagger: "2.0"
info:
  description: "Newsfeed API for hypothetical homepage application"
  version: "0.1.0"
  title: "Newsfeed"
  contact:
    email: "chris@snyder616.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "newsfeed"
basePath: "/"
tags:
- name: "newsfeed"
  description: "Newsfeed operations"
schemes:
- "http"
paths:
  /newsfeed/{userId}:
    get:
      tags:
      - "newsfeed"
      summary: "Retrieve newsfeed items"
      description: ""
      operationId: "getNewsfeedItemsByUserId"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID of user for which to retrieve newsfeed"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Newsfeed"
        404:
          description: "Newsfeed not found for provided user ID"
definitions:
  Newsfeed:
    type: "object"
    properties:
      newsItems:
        type: array
        items:
          $ref: "#/definitions/NewsItem"
  NewsItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      title:
        type: "string"
