apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app: homepage
    version: v2
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: homepage
    version: v2
