apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: homepage-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: homepage
        version: v2
    spec:
      containers:
      - name: homepage
        image: istio-demo/homepage:2.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  labels:
    app: homepage
    version: v2
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  selector:
    app: homepage
    version: v2
---
